#development:
#  acs_url: https://chalkable-local-access-control.accesscontrol.windows.net/v2/OAuth2-13
#  client_id: eq
#  client_secret: 4d8d2c33949141d8813e1f89f90234255ed92fc5db9f4b04ac45f3fd2f69ed24773195b212f8468cb99159a745d668665822d9bc45dd451b93a2f6af5ccb8265
#  scope: https://localhost/chalkable/
#  redirect_uri: http://localhost:3000/home/index
#  service_url: https://localhost/chalkable/User/Me.json
development:
  acs_url: https://chalkable-access-control.accesscontrol.windows.net/v2/OAuth2-13
  client_id: equations
  client_secret: 14209d4b3c984b2e8a3f5703d6b6edbd9cfbb5fe01bb491cadb0a08ed0db14a69cdad6ea5f534e069a2122a68fa34ef6d16fa26a3bd54e7aa0af649619dc20fe
  scope: https://chalkable.com
  redirect_uri: http://math-equations.herokuapp.com/home/index
  service_url: https://chalkable.com/User/Me.json
production:
  acs_url: https://chalkable-access-control.accesscontrol.windows.net/v2/OAuth2-13
  client_id: equations
  client_secret: 14209d4b3c984b2e8a3f5703d6b6edbd9cfbb5fe01bb491cadb0a08ed0db14a69cdad6ea5f534e069a2122a68fa34ef6d16fa26a3bd54e7aa0af649619dc20fe
  scope: https://chalkable.com
  redirect_uri: http://math-equations.herokuapp.com/home/index
  service_url: https://chalkable.com/User/Me.json
test:
